// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "ThirdPartyShell",
    platforms: [
        .iOS(.v15)
    ],
    products: [
        .library(name: "ThirdPartyShell", targets: ["ThirdPartyShell"])
    ],
    dependencies: [
        .package(path: "../Vendor/AEPAnalytics"),
        .package(path: "../Vendor/AEPAssurance"),
        .package(path: "../Vendor/AEPCore"),
        .package(path: "../Vendor/AEPEdge"),
        .package(path: "../Vendor/AEPEdgeConsent"),
        .package(path: "../Vendor/AEPEdgeIdentity"),
        .package(path: "../Vendor/AEPRulesEngine"),
        .package(path: "../Vendor/AEPTarget"),
        .package(path: "../Vendor/Alamofire"),
        .package(path: "../Vendor/AlamofireNetworkActivityLogger"),
        .package(path: "../Vendor/AppDynamicsAgent"),
        .package(path: "../Vendor/BigInt"),
        .package(path: "../Vendor/CryptoSwift"),
        .package(path: "../Vendor/DeviceKit"),
        .package(path: "../Vendor/DGCharts"),
        .package(path: "../Vendor/Differentiator"),
        .package(path: "../Vendor/FirebaseABTesting"),
        .package(path: "../Vendor/FloatingPanel"),
        .package(path: "../Vendor/GoogleDataTransport"),
        .package(path: "../Vendor/GoogleMaps"),
        .package(path: "../Vendor/GooglePlaces"),
        .package(path: "../Vendor/InsiderMobile"),
        .package(path: "../Vendor/IOSSecuritySuite"),
        .package(path: "../Vendor/iProov"),
        .package(path: "../Vendor/IQKeyboardManagerSwift"),
        .package(path: "../Vendor/ISPageControl"),
        .package(path: "../Vendor/KeychainAccess"),
        .package(path: "../Vendor/Kingfisher"),
        .package(path: "../Vendor/lottie-ios"),
        .package(path: "../Vendor/Mantis"),
        .package(path: "../Vendor/MEPSDK"),
        .package(path: "../Vendor/MGSwipeTableCell"),
        .package(path: "../Vendor/nanopb"),
        .package(path: "../Vendor/PromisesObjC"),
        .package(path: "../Vendor/RxBlocking"),
        .package(path: "../Vendor/RxKeyboard"),
        .package(path: "../Vendor/RxSwiftExt"),
        .package(path: "../Vendor/SkeletonView"),
        .package(path: "../Vendor/SVProgressHUD"),
        .package(path: "../Vendor/SwiftLint"),
        .package(path: "../Vendor/TensorFlowLiteC"),
        .package(path: "../Vendor/ZIPFoundation"),
    ],
    targets: [
        .target(
            name: "ThirdPartyShell",
            dependencies: [
                .product(name: "AEPAnalytics", package: "AEPAnalytics"),
                .product(name: "AEPAssurance", package: "AEPAssurance"),
                .product(name: "AEPCore", package: "AEPCore"),
                .product(name: "AEPIdentity", package: "AEPCore"),
                .product(name: "AEPLifecycle", package: "AEPCore"),
                .product(name: "AEPServices", package: "AEPCore"),
                .product(name: "AEPSignal", package: "AEPCore"),
                .product(name: "AEPEdge", package: "AEPEdge"),
                .product(name: "AEPEdgeConsent", package: "AEPEdgeConsent"),
                .product(name: "AEPEdgeIdentity", package: "AEPEdgeIdentity"),
                .product(name: "AEPRulesEngine", package: "AEPRulesEngine"),
                .product(name: "AEPTarget", package: "AEPTarget"),
                .product(name: "Alamofire", package: "Alamofire"),
                .product(name: "AlamofireNetworkActivityLogger", package: "AlamofireNetworkActivityLogger"),
                .product(name: "AppDynamicsAgent", package: "AppDynamicsAgent"),
                .product(name: "BigInt", package: "BigInt"),
                .product(name: "CryptoSwift", package: "CryptoSwift"),
                .product(name: "DeviceKit", package: "DeviceKit"),
                .product(name: "DGCharts", package: "DGCharts"),
                .product(name: "Differentiator", package: "Differentiator"),
                .product(name: "RxDataSources", package: "Differentiator"),
                .product(name: "FirebaseABTesting", package: "FirebaseABTesting"),
                .product(name: "FirebaseCore", package: "FirebaseABTesting"),
                .product(name: "FirebaseCrashlytics", package: "FirebaseABTesting"),
                .product(name: "FirebaseInstallations", package: "FirebaseABTesting"),
                .product(name: "FirebaseMessaging", package: "FirebaseABTesting"),
                .product(name: "FirebasePerformance", package: "FirebaseABTesting"),
                .product(name: "FirebaseRemoteConfig", package: "FirebaseABTesting"),
                .product(name: "FloatingPanel", package: "FloatingPanel"),
                .product(name: "GoogleDataTransport", package: "GoogleDataTransport"),
                .product(name: "GoogleMaps", package: "GoogleMaps"),
                .product(name: "GooglePlaces", package: "GooglePlaces"),
                .product(name: "InsiderMobile", package: "InsiderMobile"),
                .product(name: "InsiderMobileAdvancedNotification", package: "InsiderMobile"),
                .product(name: "IOSSecuritySuite", package: "IOSSecuritySuite"),
                .product(name: "iProov", package: "iProov"),
                .product(name: "IQKeyboardManagerSwift", package: "IQKeyboardManagerSwift"),
                .product(name: "ISPageControl", package: "ISPageControl"),
                .product(name: "KeychainAccess", package: "KeychainAccess"),
                .product(name: "Kingfisher", package: "Kingfisher"),
                .product(name: "lottie-ios", package: "lottie-ios"),
                .product(name: "Mantis", package: "Mantis"),
                .product(name: "MEPSDK", package: "MEPSDK"),
                .product(name: "MGSwipeTableCell", package: "MGSwipeTableCell"),
                .product(name: "nanopb", package: "nanopb"),
                .product(name: "PromisesObjC", package: "PromisesObjC"),
                .product(name: "RxBlocking", package: "RxBlocking"),
                .product(name: "RxCocoa", package: "RxBlocking"),
                .product(name: "RxRelay", package: "RxBlocking"),
                .product(name: "RxSwift", package: "RxBlocking"),
                .product(name: "RxTest", package: "RxBlocking"),
                .product(name: "RxKeyboard", package: "RxKeyboard"),
                .product(name: "RxSwiftExt", package: "RxSwiftExt"),
                .product(name: "SkeletonView", package: "SkeletonView"),
                .product(name: "SVProgressHUD", package: "SVProgressHUD"),
                .product(name: "SwiftLint", package: "SwiftLint"),
                .product(name: "TensorFlowLiteC", package: "TensorFlowLiteC"),
                .product(name: "ZIPFoundation", package: "ZIPFoundation"),
            ]
        )
    ]
)
