// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "ExternalPackages",
    platforms: [
        .iOS(.v15)
    ],
    products: [
        .library(name: "ExternalPackages", targets: ["ExternalPackages"])
    ],
    dependencies: [
        .package(path: "External/AEPAnalytics"),
        .package(path: "External/AEPAssurance"),
        .package(path: "External/AEPCore"),
        .package(path: "External/AEPEdge"),
        .package(path: "External/AEPEdgeConsent"),
        .package(path: "External/AEPEdgeIdentity"),
        .package(path: "External/AEPRulesEngine"),
        .package(path: "External/AEPTarget"),
        .package(path: "External/Alamofire"),
        .package(path: "External/AppDynamicsAgent"),
        .package(path: "External/BigInt"),
        .package(path: "External/CryptoSwift"),
        .package(path: "External/DeviceKit"),
        .package(path: "External/DGCharts"),
        .package(path: "External/Firebase"),
        .package(path: "External/FloatingPanel"),
        .package(path: "External/GoogleDataTransport"),
        .package(path: "External/GoogleMaps"),
        .package(path: "External/GooglePlaces"),
        .package(path: "External/Insider"),
        .package(path: "External/IOSSecuritySuite"),
        .package(path: "External/iProov"),
        .package(path: "External/IQKeyboardManagerSwift"),
        .package(path: "External/ISPageControl"),
        .package(path: "External/KeychainAccess"),
        .package(path: "External/Kingfisher"),
        .package(path: "External/Lottie"),
        .package(path: "External/Mantis"),
        .package(path: "External/MEPSDK"),
        .package(path: "External/MGSwipeTableCell"),
        .package(path: "External/mobile-sdk-ios"),
        .package(path: "External/nanopb"),
        .package(path: "External/Promises"),
        .package(path: "External/RxDataSources"),
        .package(path: "External/RxKeyboard"),
        .package(path: "External/RxSwift"),
        .package(path: "External/RxSwiftExt"),
        .package(path: "External/SkeletonView"),
        .package(path: "External/SVProgressHUD"),
        .package(path: "External/TensorFlowLiteC"),
        .package(path: "External/ZIPFoundation"),
    ],
    targets: [
        .target(
            name: "ExternalPackages",
            dependencies: [
                .product(name: "AEPAnalytics", package: "AEPAnalytics"),
                .product(name: "AEPAssurance", package: "AEPAssurance"),
                .product(name: "AEPCore", package: "AEPCore"),
                .product(name: "AEPIdentity", package: "AEPCore"),
                .product(name: "AEPLifecycle", package: "AEPCore"),
                .product(name: "AEPServices", package: "AEPCore"),
                .product(name: "AEPSignal", package: "AEPCore"),
                .product(name: "AEPEdge", package: "AEPEdge"),
                .product(name: "AEPEdgeConsent", package: "AEPEdgeConsent"),
                .product(name: "AEPEdgeIdentity", package: "AEPEdgeIdentity"),
                .product(name: "AEPRulesEngine", package: "AEPRulesEngine"),
                .product(name: "AEPTarget", package: "AEPTarget"),
                .product(name: "Alamofire", package: "Alamofire"),
                .product(name: "AppDynamicsAgent", package: "AppDynamicsAgent"),
                .product(name: "BigInt", package: "BigInt"),
                .product(name: "CryptoSwift", package: "CryptoSwift"),
                .product(name: "DeviceKit", package: "DeviceKit"),
                .product(name: "DGCharts", package: "DGCharts"),
                .product(name: "FirebaseCrashlytics", package: "Firebase"),
                .product(name: "FirebaseInstallations", package: "Firebase"),
                .product(name: "FirebaseMessaging", package: "Firebase"),
                .product(name: "FirebasePerformance", package: "Firebase"),
                .product(name: "FirebaseRemoteConfig", package: "Firebase"),
                .product(name: "FloatingPanel", package: "FloatingPanel"),
                .product(name: "GoogleDataTransport", package: "GoogleDataTransport"),
                .product(name: "GoogleMaps", package: "GoogleMaps"),
                .product(name: "GooglePlaces", package: "GooglePlaces"),
                .product(name: "InsiderMobile", package: "Insider"),
                .product(name: "InsiderMobileAdvancedNotification", package: "Insider"),
                .product(name: "IOSSecuritySuite", package: "IOSSecuritySuite"),
                .product(name: "iProov", package: "iProov"),
                .product(name: "IQKeyboardManagerSwift", package: "IQKeyboardManagerSwift"),
                .product(name: "ISPageControl", package: "ISPageControl"),
                .product(name: "KeychainAccess", package: "KeychainAccess"),
                .product(name: "Kingfisher", package: "Kingfisher"),
                .product(name: "Lottie", package: "Lottie"),
                .product(name: "Mantis", package: "Mantis"),
                .product(name: "MEPSDK", package: "MEPSDK"),
                .product(name: "MGSwipeTableCell", package: "MGSwipeTableCell"),
                .product(name: "Jumio", package: "mobile-sdk-ios"),
                .product(name: "JumioIProov", package: "mobile-sdk-ios"),
                .product(name: "JumioLiveness", package: "mobile-sdk-ios"),
                .product(name: "JumioDefaultUI", package: "mobile-sdk-ios"),
                .product(name: "JumioLocalization", package: "mobile-sdk-ios"),
                .product(name: "nanopb", package: "nanopb"),
                .product(name: "Promises", package: "Promises"),
                .product(name: "Differentiator", package: "RxDataSources"),
                .product(name: "RxDataSources", package: "RxDataSources"),
                .product(name: "RxKeyboard", package: "RxKeyboard"),
                .product(name: "RxBlocking", package: "RxSwift"),
                .product(name: "RxCocoa", package: "RxSwift"),
                .product(name: "RxRelay", package: "RxSwift"),
                .product(name: "RxSwift", package: "RxSwift"),
                .product(name: "RxTest", package: "RxSwift"),
                .product(name: "RxSwiftExt", package: "RxSwiftExt"),
                .product(name: "SkeletonView", package: "SkeletonView"),
                .product(name: "SVProgressHUD", package: "SVProgressHUD"),
                .product(name: "TensorFlowLiteC", package: "TensorFlowLiteC"),
                .product(name: "ZIPFoundation", package: "ZIPFoundation"),
            ]
        )
    ]
)
