osx_image: xcode12.3
language: objective-c
sudo: required
env:
  global:
    - PROJECT="RxKeyboard.xcodeproj"
    - SCHEME="RxKeyboard-Package"
    - IOS_SDK="iphonesimulator"
    - MACOS_SDK="macosx11.0"
    - TVOS_SDK="appletvsimulator9.0"
    - WATCHOS_SDK="watchsimulator3.0"
    - FRAMEWORK="RxKeyboard"
  matrix:
    - SDK="$IOS_SDK"      TEST=0  SWIFT_VERSION=5.1 DESTINATION="platform=iOS Simulator,name=iPhone 8"

install:
  - swift --version
  - bundle install

before_script:
  - set -o pipefail
  - swift package generate-xcodeproj

script:
  - if [ $TEST == 1 ]; then
      xcodebuild clean SWIFT_VERSION=${SWIFT_VERSION} build test
        -project "$PROJECT"
        -scheme "$SCHEME"
        -sdk "$SDK"
        -destination "$DESTINATION"
        -configuration Debug
        -enableCodeCoverage YES
        CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c;
    else
      xcodebuild clean SWIFT_VERSION=${SWIFT_VERSION} build
        -project "$PROJECT"
        -scheme "$SCHEME"
        -sdk "$SDK"
        -destination "$DESTINATION"
        -configuration Debug
        CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c;
    fi
  - bundle exec pod repo update
  - bundle exec pod lib lint --swift-version=${SWIFT_VERSION} --verbose --allow-warnings --fail-fast

before_deploy:
  - bundle exec swiftproj generate-xcconfig --podspec RxKeyboard.podspec
  - bundle exec swiftproj generate-xcodeproj --xcconfig-overrides Config.xcconfig
  - bundle exec swiftproj configure-scheme --project RxKeyboard.xcodeproj --scheme RxKeyboard-Package --buildable-targets RxKeyboard
  - bundle exec swiftproj remove-framework --project RxKeyboard.xcodeproj --target RxKeyboard --framework RxCocoa.framework
  - bundle exec swiftproj remove-framework --project RxKeyboard.xcodeproj --target RxKeyboard --framework RxCocoaRuntime.framework
  - ./carthage.sh bootstrap
  - carthage build --no-skip-current --verbose | xcpretty -c
  - carthage archive RxKeyboard

deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  file: $FRAMEWORK.framework.zip
  skip_cleanup: true
  on:
    repo: RxSwiftCommunity/RxKeyboard
    tags: true
    condition: $SDK = $IOS_SDK
