install! 'cocoapods', :integrate_targets => false

platform :ios, '14.0'
use_frameworks! :linkage => :static
inhibit_all_warnings!

target 'CocoaPodsClonerSample' do
  pod 'Alamofire', '~> 5.9'
  pod 'SnapKit', '~> 5.7'
end
