name: ci

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  spm:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build

  cocoapods:
      strategy:
          matrix:
            platform: [ios, tvos, macos, watchos]
      runs-on: macOS-latest
      steps:
      - uses: actions/checkout@v4
      - name: Build
        # Some header files import C++ headers, which causes linting failures
        # (https://github.com/CocoaPods/CocoaPods/issues/5152). As a
        # workaround, the `--skip-import-validation` is used.
        run: |
          pod lib lint leveldb-library.podspec \
            --platforms=${{ matrix.platform }} \
            --skip-import-validation
